export const INIT_STATE = 'INIT';

export const RESOLVING_TREE_DEPENDENCIES_STATE = 'RESOLVING_TREE_DEPENDENCIES';
export const TREE_DEPENDENCIES_RESOLVED_STATE = 'TREE_DEPENDENCIES_RESOLVED';

export const DEPENDENCIES_RESOLVED_STATE = 'DEPENDENCIES_RESOLVED';

export const EXECUTING_COMMAND_STATE = 'EXECUTING_COMMAND';
export const COMMAND_EXECUTED_STATE = 'COMMAND_EXECUTED';